# Generated by Django 2.1.7 on 2019-04-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190413_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmulti',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='commentmulti_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentmulti',
            name='comment_user',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='commentmulti_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
